esphome:
  name: pelletkachel
  friendly_name: Pellet Kachel
  on_boot:
    - priority: -10
      then: 
        - lambda: |- 
            id(uart_send) = 0;
            id(room_temp_stove).publish_state(17.0);
            id(power_level).publish_state(1);
            id(pellet_speed).publish_state(1);
            id(fan_mode) = 1;
            id(flu_gas_temp).publish_state(17.0);
            id(exh_fan_speed).publish_state(0);
            id(burner_status).publish_state("All OK, startup");
            id(Stove).target_temperature = 21.0;

esp8266:
  board: d1

packages:
  remote_package_files:
    url: https://github.com/mvroosmalen1970/ESPHome-Duepi
    files: [script.yaml, api.yaml, globals.yaml, sensor.yaml, switch.yaml, climate.yaml, uart.yaml, time.yaml, text_sensor.yaml]
    ref: main  

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart
  
ota:
  - platform: esphome
    password: "CreateYourOwn"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid1
      password: !secret wifi_password1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pelletkachel Fallback Hotspot"
    password: "Pelletkachel"

captive_portal:

   

