esphome:
  name: pelletkachel
  friendly_name: Pellet Kachel
  on_boot:
    priority: -10
    then:
      - lambda: |-
          id(fan_mode) = 3;

api:
  encryption:
    key: !secret encryption_key

esp8266:
  board: d1

#use this for esp-c3 mini
#esp32
  #board: lolin_c3_mini
  #framework:
    #type: esp-idf
  
ota:
  - platform: esphome
    password: "CreateYourOwn"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid1
      password: !secret wifi_password1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pelletkachel Fallback Hotspot"
    password: "Pelletkachel"

packages:
  remote_package_files:
    url: https://github.com/mvroosmalen1970/ESPHome-Duepi.git
    files: [
      components/script.yaml, 
      components/globals.yaml, 
      components/sensor.yaml, 
      components/switch.yaml, 
      components/climate.yaml, 
      components/uart.yaml, 
      components/time.yaml, 
      components/text_sensor.yaml
      ]
    ref: main #change if you like to test a beta version
    refresh: 0d
    
globals:
  - id: stove_is_heating
    type: bool
    restore_value: no
    initial_value: "false"
